
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 6;
  public static final int MAS = 2;
  public static final int error = 1;
  public static final int PDER = 5;
  public static final int PIZQ = 4;
  public static final int POR = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "POR",
  "PIZQ",
  "PDER",
  "NUM"
  };
}

